/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author Andres
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        primernumero = new javax.swing.JTextField();
        segundonumero = new javax.swing.JTextField();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        raiza = new javax.swing.JButton();
        raizb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calculadora");

        jLabel2.setText("Ingrese el primer número");

        jLabel3.setText("Ingrese el segundo número");

        sumar.setText("Sumar(a+b)");
        sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarMouseClicked(evt);
            }
        });

        restar.setText("Restar(a-b)");
        restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restarMouseClicked(evt);
            }
        });

        multiplicar.setText("Multiplicar(a*b)");
        multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicarMouseClicked(evt);
            }
        });

        dividir.setText("Dividir(a/b)");
        dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividirMouseClicked(evt);
            }
        });

        raiza.setText("Raíz(a)");
        raiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raizaMouseClicked(evt);
            }
        });

        raizb.setText("Raíz(b)");
        raizb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raizbMouseClicked(evt);
            }
        });
        raizb.addActionListener(this::raizbActionPerformed);

        jLabel4.setText("(a)");

        jLabel5.setText("(b)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(segundonumero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(primernumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(restar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dividir)
                            .addGap(30, 30, 30)
                            .addComponent(raizb))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sumar)
                            .addGap(18, 18, 18)
                            .addComponent(multiplicar)
                            .addGap(18, 18, 18)
                            .addComponent(raiza))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(primernumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(segundonumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumar)
                    .addComponent(multiplicar)
                    .addComponent(raiza))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restar)
                    .addComponent(dividir)
                    .addComponent(raizb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raizbActionPerformed

    private void sumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumarMouseClicked
        try{
            double suma = Double.parseDouble(primernumero.getText()) + Double.parseDouble(segundonumero.getText());
            resultado.setText(String.valueOf(suma));
        }
        catch (NumberFormatException e){
            resultado.setText("Error, debe ingresar números");
        }
    }//GEN-LAST:event_sumarMouseClicked

    private void restarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restarMouseClicked
        try{
            double resta = Double.parseDouble(primernumero.getText()) - Double.parseDouble(segundonumero.getText());
            resultado.setText(String.valueOf(resta));
        }
        catch (NumberFormatException e){
            resultado.setText("Error, debe ingresar números");
        }
    }//GEN-LAST:event_restarMouseClicked

    private void multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicarMouseClicked
        try{
            double multi = Double.parseDouble(primernumero.getText()) * Double.parseDouble(segundonumero.getText());
            resultado.setText(String.valueOf(multi));
        }
        catch (NumberFormatException e){
            resultado.setText("Error, debe ingresar números");
        }
    }//GEN-LAST:event_multiplicarMouseClicked

    private void dividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividirMouseClicked
        try{
            if (Double.parseDouble(segundonumero.getText())==0){
                throw new ArithmeticException();
            }
            double div = Double.parseDouble(primernumero.getText()) / Double.parseDouble(segundonumero.getText());
            resultado.setText(String.valueOf(Math.round(div*100.00)/100.00));
        }
        catch (ArithmeticException e){
            resultado.setText("Error, debe no se puede dividir entre cero");
        }
        catch (NumberFormatException e){
            resultado.setText("Error, debe ingresar números");
        }
    }//GEN-LAST:event_dividirMouseClicked

    private void raizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizaMouseClicked
        try{
            double numero = Double.parseDouble(primernumero.getText());
            if (numero<0){
                throw new ArithmeticException();
            }
            calcularraiz(numero);
        } catch (ArithmeticException e) {
            resultado.setText("Error: raíz de número negativo");
        } catch (NumberFormatException e) {
            resultado.setText("Error: debe ingresar un número");
        }
    }//GEN-LAST:event_raizaMouseClicked

    private void raizbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizbMouseClicked
        try{
            double numero = Double.parseDouble(segundonumero.getText());
            if (numero<0){
                throw new ArithmeticException();
            }
            calcularraiz(numero);
        } catch (ArithmeticException e) {
            resultado.setText("Error: raíz de número negativo");
        } catch (NumberFormatException e) {
            resultado.setText("Error: debe ingresar un número");
        }
    }//GEN-LAST:event_raizbMouseClicked

    public void calcularraiz(double numero){
        resultado.setText(String.valueOf(Math.round(Math.sqrt(numero)*100.00)/100.00));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dividir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton multiplicar;
    private javax.swing.JTextField primernumero;
    private javax.swing.JButton raiza;
    private javax.swing.JButton raizb;
    private javax.swing.JButton restar;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField segundonumero;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
